--this is the DDL to create the database.

--creating compounds' entity's table 
CREATE TABLE Compounds (
	Candidate_ID VARCHAR(10) UNIQUE NOT NULL,
	Molecule_Name VARCHAR(250),
	Formula VARCHAR(1000) NOT NULL,
	Structure BLOB NOT NULL,
	IUPAC VARCHAR(1500),
	Molecule_Number INT NOT NULL,
	Molecular_Weight DECIMAL(10,3) NOT NULL,
	Exact_Molecular_Weight DECIMAL(10,3) NOT NULL,
	LogP DECIMAL(10,3) NOT NULL,
	LogD DECIMAL(10,3) NOT NULL,
	Hydrogen_Bond_Donors INT NOT NULL,
	Hydrogen_Bond_Acceptors INT NOT NULL,
	Rotatable_Bonds INT NOT NULL,
	Number_of_Rings INT NOT NULL,
	TPSA DECIMAL(10,3) NOT NULL,
	Number_of_Aromatic_Rings INT NOT NULL,
	Number_of_Fused_Aromatic_Rings INT NOT NULL,
	SMILES VARCHAR(250),
	QED DECIMAL(10,3) NOT NULL,
	SPS DECIMAL(10,3) NOT NULL,
	Valence_Electrons INT NOT NULL,
	Radical_Electrons INT NOT NULL,
	Molar_Refractivity DECIMAL(10,3) NOT NULL,
	Number_of_Atoms INT NOT NULL,
	Formal_Charge INT NOT NULL,
	Number_of_Heavy_Atoms INT NOT NULL,
	Lipinski_Score CHAR(1) NOT NULL,
	Lead_Likeness_Score CHAR(1) NOT NULL,
	Bioavailability_Score CHAR(1) NOT NULL,
	Ghose_Score CHAR(1) NOT NULL,
	Veber_Score CHAR(1) NOT NULL,
	REOS_Score CHAR(1) NOT NULL,
	Rule_of_3_Score CHAR(1) NOT NULL,
	Drug_Like_QED_Score CHAR(1) NOT NULL,
	All_Filters_Test BOOLEAN NOT NULL,
	PRIMARY KEY (Candidate_ID)
);